import {
  ArrowDownToLine,
  ArrowRight,
  ArrowUpRight,
  Award,
  Braces,
  Cat,
  ChevronLeft,
  ChevronRight,
  Code2,
  Command,
  Cpu,
  FileText,
  FlaskConical,
  Folder,
  Github,
  Layers3,
  Linkedin,
  Mail,
  Moon,
  Maximize2,
  Minimize2,
  Minus,
  Network,
  Pause,
  Play,
  Route,
  ScanLine,
  Search,
  Sparkles,
  Sun,
  Terminal,
  UserRound,
  X,
} from "lucide-react";

const icons = {
  user: UserRound,
  award: Award,
  route: Route,
  terminal: Terminal,
  folder: Folder,
  file: FileText,
  mail: Mail,
  scan: ScanLine,
  spark: Sparkles,
  network: Network,
  layers: Layers3,
  flask: FlaskConical,
  code: Code2,
  cpu: Cpu,
  command: Command,
  search: Search,
  arrow: ArrowRight,
  external: ArrowUpRight,
  download: ArrowDownToLine,
  github: Github,
  linkedin: Linkedin,
  close: X,
  minus: Minus,
  maximize: Maximize2,
  minimize: Minimize2,
  braces: Braces,
  cat: Cat,
  previous: ChevronLeft,
  next: ChevronRight,
  pause: Pause,
  play: Play,
  sun: Sun,
  moon: Moon,
};
export function Icon({
  name,
  size = 18,
  className = "",
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Component = icons[name as keyof typeof icons] ?? Terminal;
  return <Component size={size} strokeWidth={1.5} className={className} aria-hidden="true" />;
}
